# Generated by Django 3.2.8 on 2021-10-28 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='baseuser_ptr',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='panchayath_name',
        ),
        migrations.RemoveField(
            model_name='panchayath',
            name='baseuser_ptr',
        ),
        migrations.DeleteModel(
            name='BaseUser',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Panchayath',
        ),
    ]
