# Generated by Django 3.2.8 on 2021-11-18 14:18

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_baseuser_employee_panchayath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='panchayath',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='panchayath',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='panchayath',
            name='pincode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='panchayath',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
                ('ta', models.IntegerField()),
                ('da', models.IntegerField()),
                ('credited_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='users.employee')),
                ('panchayath_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='users.panchayath')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('panchayath_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='users.panchayath')),
            ],
        ),
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.baseuser')),
                ('enduser_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('address', models.TextField(default='')),
                ('phone', models.CharField(default=None, max_length=100)),
                ('panchayath_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enduser', to='users.panchayath')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.baseuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('solved', models.BooleanField(default=False)),
                ('enduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.enduser')),
                ('panchayath_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='users.panchayath')),
            ],
        ),
    ]
